<?php

namespace DDK\API;


class Method
{
    const GET_ACCOUNT = 'GET_ACCOUNT';
    const GET_ACCOUNT_BALANCE = 'GET_ACCOUNT_BALANCE';
    const GET_TRANSACTION = 'GET_TRANSACTION';
    const GET_TRANSACTIONS_BY_BLOCK_ID = 'GET_TRANSACTIONS_BY_BLOCK_ID';
    const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
    const CREATE_TRANSACTION = 'CREATE_TRANSACTION';

}
